import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "animate.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

import MainLayout from "./components/layout/MainLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Suncart Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">

        <MainLayout>
          {children}
        </MainLayout>

        <ToastContainer
          position="top-right"
          autoClose={3000}
        />

      </body>
    </html>
  );
}